INSERT INTO USER (USERNAME, PASSWORD, ACTIVE) VALUES ('rampageJackson@admin.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ACTIVE) VALUES ('mcgregor@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ACTIVE) VALUES ('test@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ACTIVE) VALUES ('test1@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ACTIVE) VALUES ('test2@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ACTIVE) VALUES ('test3@outlook.com','12345',TRUE);
