#+TITLE: Projets GTM

Ce dépôt contient les projets réalisés lors de ma formation
Java/Angular ayant eu lieu du 26/02/2018 au 28/05/2018.

Les projets ProxiBanque v2 à 4 ont leur dépôt dédié et sont donc
inclus sous forme de sous-modules. Afin de cloner le dépôt en incluant
les sous-modules, utiliser la commande suivante :

#+BEGIN_SRC sh
  git clone --recurse-submodules https://github.com/alecigne/gtm-projects
#+END_SRC

Chaque projet inclut un fichier =.gitignore= qui va exclure de la
gestion de versions les fichiers spécifiques à l'IDE utilisé lors de
cette formation (Eclipse). La plupart des projets réalisés avant
l'utilisation de Maven doivent donc faire l'objet d'étapes de
configuration supplémentaires afin d'être totalement fonctionnels,
typiquement : association de Tomcat, de la librairie JUnit, etc. Ces
étapes sont autant que possible mentionnées dans le fichier README
associé à chaque projet.

Consulter également le [[https://github.com/alecigne/gtm-projects/wiki][wiki]]. Lorsque nécessaire, les fichiers README
des projets y font référence.

* Index des projets

Ci-dessous, un index découpé en sections correspondants aux différents
modules de la formation.

** Java 1

aa_GestionFormations | ab_Bonjour | ac_PremierProjet |
ad_PremierLivrable | ae_TPFonctionnelle | af_GuessMyNumber |
ag_GuessMyNumber2 | ah_PairImpair | ai_ForLoops | aj_Objet |
ak_Constructeur | al_Constructeur | am_Constructeur |
an_Polymorphisme | ao_ClubManager

** Java 2

ap_Formations | aq_SimpleInterface | ar_Pattern | as_TPInterfaces |
at_TemplateMethod | au_Characters | av_Butterflies | aw_Genericite |
ax_Formations | ay_TPInterfacesCollections | az_Vehicles |
ba_ModeleEnCouche

** Git

bd_Exceptions

** Bases de données

be_Projet1 | bf_Projet2 | bg_Projet3 | bh_Projet4 | bi_Projet5

** HTML/CSS

bj_TPStringBuilder | bk_CV | bl_RollOver | bm_Selecteurs |
bn_Colonnes | bo_Bootstrap

** API Servlet

bp_GestionFormations | bq_TestServlet | br_Servlet2 | bs_JSP1 |
bt_LoginPassword | bu_jspThreadScope | bv_Session | bw_Session2 |
bx_MVC | by_mvc-exercises | bz_sql

** Maven

cb_FirstMaven | cc_MavenCalculator

** ORM

cd_Hibernate01 | ce_OneToOne | cf_OneToMany | cg_OneToManyJPA |
ch_ManyToManyJPA | ci_GestionSallesJPA

** EJB

cj_TestWildfly | ck_HelloEjbWar | cl_HelloEjbWar

** WebServices

cm_PatientXML | cn_TPJAXB | co_TPJAXB2 | cp_TPJAXB2_corr |
cq_Firstws_Morane | cr_FirstWS | cs_restws

** Design patterns

ct_Cohesion_Decouplage | cu_DaoFactoryStep01 |
cv_Cohesion_Decouplage | cw_Patterns | cx_Locales

** JavaScript

cy_Logs | cz_OrderProcessingMaven | da_OrderProcessingMaven |
db_JSIntro | dc_JSCheckboxes | dd_Selecteurs

** Spring

df_PrestiBanque_TP1_setter | dg_PrestiBanque_TP1_constructeur |
dh_PrestiBanque_TP2_scope | di_PrestiBanque_TP2_scope_corr |
dj_PrestiBanque_TP2b | dk_SpringVehicleXML |
dl_SpringVehicleAnnotations | dm_PrestiBanque_TP3 | dn_TP3_corr |
do_TP4_Autowire | dp_TP4 | dq_PrestiBanque_TP5 | dr_PrestiBanque_TP5 |
dr_TP5-Config_Morane | ds_PrestiBanque_TP5 |
dt_PrestiBanque_TP5_primary | du_PrestiBanque_TP5_qualifier |
dv_PrestiBanque_TP5_resource | dw_SpringVehicle_Annotations_alc |
dx_SpringVehicle_AutoXML_alc | dy_SpringVehicle_FullXML_alc |
dz_TP5_couches | ea_TP5_couches_XML | eb_TP5b | ec_TPSimpleUnitTests |
ed_TP6_hibernate | ee_AOPConcert | ef_SpringJPA |
eg_TP6_SpringDataJPA | eh_simpleMavenJPA

** Java Security

ei_SimpleAuth | ej_SimpleLogin | ek_springsecurity0 |
el_simpleMavenJPAWeb | em_simpleMavenJPAWebFinal

** Angular

en_vm-starter-final | eo_vm-starter-git | ep_superquiz | eq_superquiz-final | er_proxibanque

** ProxiBanque

bb_ProxiBanqueSI_v1.0 | bc_ProxiBanqueSI_v1.1 |
ca_ProxiBanqueSI_jmh_alc | de_ProxiBanquesi_slm_alc |
es_ProxiBanqueSI_v4_cs_slm_alc

* ProxiBanque

** bb_ProxiBanqueSI_v1.0

Première version du projet ProxiBanqueSI, avec données stockées en
mémoire.

- IHM : CLI, Java SE 8
- Backend : Java SE 8
- Persistance : mémoire (hashmap)

** bc_ProxiBanqueSI_v1.1

Ce projet est une tentative d'amélioration du projet v1.0, restée sans
suite.

** ca_ProxiBanqueSI_jmh_alc

Deuxième version du projet ProxiBanqueSI.

- IHM : Web, API Java Servlet
- Backend : Java SE 8
- Persistance : JDBC, MySQL

** de_ProxiBanquesi_slm_alc

Troisième version du projet ProxiBanqueSI.

- IHM : aucune, élaboration d'une API REST. Présence cependant d'un
  système de page d'accueil avec login et filtre basé sur l'API Java
  Servlet.
- Backend : Java SE 8
- Persistance : ORM (Hibernate), MySQL

** es_ProxiBanqueSI_v4_cs_slm_alc

Quatrième et dernière version du projet ProxiBanqueSI.

- IHM : Angular 5
- Backend : Java SE 8, Spring
- Persistance : ORM (Hibernate), MySQL
