INSERT INTO VOITURE (MODEL, KM) VALUES ('Renault','10000');
INSERT INTO VOITURE (MODEL, KM) VALUES ('Peugeot','20000');
INSERT INTO VOITURE (MODEL, KM) VALUES ('Fiat','30000');
INSERT INTO VOITURE (MODEL, KM) VALUES ('Volvo','40000');
INSERT INTO VOITURE (MODEL, KM) VALUES ('Citroen','50000');
INSERT INTO VOITURE (MODEL, KM) VALUES ('Honda','60000');
